name: Build and Release (PyInstaller)

on:
  push:
    tags:
      - 'v*'         # <-- Workflow uruchomi się tylko przy pushu tagu zaczynającego się od v

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'   # W razie potrzeby zmień na inną wersję

      - name: Install PyInstaller
        run: |
          pip install --upgrade pip
          pip install pyinstaller

      - name: Build exe using PyInstaller
        run: |
          pyinstaller --onefile --noconsole getTelegram.py
        # Po tym kroku w folderze dist/ będzie plik getTelegram.exe

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist\getTelegram.exe  # Ścieżka do pliku wykonywalnego
          asset_name: getTelegram.exe       # Nazwa, która pojawi się w Release
          asset_content_type: application/octet-stream
