name: Build and Release (PyInstaller)

on:
  push:
    tags:
      - 'v*'  # Uruchamia workflow przy tagach zaczynających się na "v"

permissions:
  contents: write  # Still needed, but the PAT overrides for the steps

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }} # Explicitly checkout the tag

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PyInstaller
        run: |
          pip install --upgrade pip
          pip install pyinstaller

      - name: Build exe using PyInstaller
        run: |
          pyinstaller --onefile --noconsole getTelegram.py

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_UPLOAD_TOKEN }}  # Use the PAT here!

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist\getTelegram.exe
          asset_name: getTelegram.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}  # Use the PAT here!
