name: Build and Release (PyInstaller)

on:
  push:
    tags:
      - 'v*'  # Uruchamiaj workflow przy tagach zaczynających się na "v"

permissions:
  contents: write  # Kluczowe, by móc stworzyć Release i załączyć asset

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Zmień, jeśli potrzebujesz innej wersji Pythona

      - name: Install PyInstaller
        run: |
          pip install --upgrade pip
          pip install pyinstaller

      - name: Build exe using PyInstaller
        run: |
          pyinstaller --onefile --noconsole getTelegram.py
        # Wynikowy plik .exe znajdziesz w katalogu dist\

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}          # np. "v1.0"
          release_name: "Release ${{ github.ref }}"  # np. "Release refs/tags/v1.0"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token do tworzenia Release

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist\getTelegram.exe          # Ścieżka do zbudowanego exe
          asset_name: getTelegram.exe               # Nazwa pliku w Release
          asset_content_type: application/octet-stream
